networks:
    workframe_network:
        name: workframe_network

services:
    workframe_nginx:
        image: nginx:alpine
        container_name: workframe_nginx
        restart: always
        env_file: ".env"
        ports:
            - "${HTTP_PORT}:80"
        networks:
            - workframe_network
        volumes:
            - ".:/var/www/html:rw"
            - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - workframe_php
            - workframe_db

    workframe_php:
        container_name: workframe_php
        restart: always
        env_file: ".env"
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
            args:
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
        networks:
            - workframe_network
        volumes:
            - ".:/var/www/html:rw"
            - "../alxarafe:/var/www/alxarafe:rw"
        extra_hosts:
            - "host.docker.internal:host-gateway"

    workframe_db:
        image: mariadb:10.11
        container_name: workframe_db
        restart: always
        env_file: ".env"
        ports:
            - "${MARIADB_PORT}:3306"
        environment:
            - MARIADB_DATABASE=${MARIADB_DATABASE}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        networks:
            - workframe_network
        volumes:
            - "workframe_db_data:/var/lib/mysql"

    workframe_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: workframe_phpmyadmin
        restart: always
        env_file: ".env"
        ports:
            - "${PHPMYADMIN_PORT}:80"
        environment:
            - PMA_HOST=workframe_db
            - PMA_PORT=3306
            - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        networks:
            - workframe_network
        depends_on:
            - workframe_db

volumes:
    workframe_db_data:
